on: [push, workflow_dispatch]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker run -v $(pwd):/workdir -w /workdir texlive/texlive latexmk --synctex=0
      - uses: actions/upload-artifact@v3
        with:
          name: thesis.pdf
          path: ubc_2022_november_chan_jonathan.pdf
      - run: docker run -v $(pwd):/workdir -w /workdir texlive/texlive latexmk --synctex=0 --jobname=POPL23 POPL23.tex
      - uses: actions/upload-artifact@v3
        with:
          name: POPL23.pdf
          path: POPL23.pdf
